### ISSUE TITLE
Missing class CallControl in Media.Devices

### ISSUE THREAD

**Issue by kirwinrMK** [pywinrt/python-winsdk#9]
I need to activate my bluetooth device's ringer and as far as I can tell it's in this class. I looked at the winsdk repository to generate my own but I'm not sure how to use it. Can this class be added or can you point me to some documentation on how to generate my own?

**Comment by dlech** [comment]
According to [the doc](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Devices.CallControl?view=winrt-22000), this API is part of `Windows Desktop Extension SDK (introduced in 10.0.10240.0)`, so it is not part of the base Windows SDK that this library is generated from. It is not clear to me if this is something that could be available outside of UWP apps or not.

**Comment by dlech** [comment]
I found the Extension SDKs at `C:\Program Files (x86)\Windows Kits\10\` and I don't see any `.winmd` metadata files there, so I'm guessing that the answer is that it is not possible at this time.

**Comment by kirwinrMK** [comment]
Thank you, I'm new to windows apps and didn't realize some of them were not available outside UWP apps.

**Comment by dlech** [comment]
Update: It turns out that enabling Extension SDKs was almost trivial. We just had to add a `+` on the SDK version in the args passed to `cppwinrt.exe` and `pywinrt.exe`. There was a bug in the PyWinRT command line reader that had to be fixed, but after that, it seems to be working. I haven't actually tried it yet, but the `CallControl ` class should be available in v1.0.0-beta.5.
